### ISSUE TITLE
remove a 'mode' in a filter

### ISSUE THREAD

**Issue by thomgb** [loicsander/Robofont-scripts#12]
Are you able to remove the boolean once a filter has one?
The whole extension explodes when I try... :)

**Comment by loicsander** [comment]
I can’t seem to reproduce this problem, could you provide some more details, how many filters in the group, using pens or functions?

**Comment by thomgb** [comment]
[Find here my pens/filters] (https://github.com/thomgb/RoboFontScripts/tree/master/pens) 

For the test a used: 
- Spike
- RemoveOverlap - difference - initial

This filter give a aura-spikey effect. :)

Then I double click 'difference' and delete the word. Whatever I do next, it no good. I can close the window and reopen the extension. Then the damage will be clearly visible... The list is not there and the SpaceCenter empty or messed up...

The moment I hit enter when I remove _difference_. The output window pops up but no message.

screens for the damage:
![screen shot 2015-05-02 at 18 25 00](https://cloud.githubusercontent.com/assets/1517937/7441824/c1ae5b1e-f0f8-11e4-9bea-e961d7d71c65.png)
![screen shot 2015-05-02 at 18 24 46](https://cloud.githubusercontent.com/assets/1517937/7441827/d410c454-f0f8-11e4-8b76-b44b2475a4c0.png)


hope it helps :)

**Comment by loicsander** [comment]
Thanks for the details, I’ll look into this.

**Comment by loicsander** [comment]
Okay, this is weird, I tried your setup, and changed the mode, everything went fine.

![capture d ecran 2015-05-02 a 18 50 55](https://cloud.githubusercontent.com/assets/5807259/7441898/448e71e2-f0fc-11e4-9d4a-0f7ec4cc62c0.png)

**Comment by thomgb** [comment]
Alright, maybe its my system. I use OS 10,10,3.

**Comment by loicsander** [comment]
I’ve modified a number of things internally, maybe these fixes solved the issue. You can try with the last version. If the issue remains, then it’s linked to something else, maybe your system yes. We can still try to figure out what the problem is.

**Comment by thomgb** [comment]
Great! I look tomorrow! :) Thanks.

**Comment by loicsander** [comment]
Also, you can achieve the same result by doing this:

Filter group:
– Spike, mode:None, initial:False
– copy, mode:union, initial:True

I added a base ‘copy’ filter, so you copy the initial glyph and make a ‘union’ boolean operation on the spiked glyph.

**Comment by thomgb** [comment]
I have still the same trouble with removing 'mode'.

Also now I unable to make groups. as soon as the Ext. is close there gone. You want this issue in a new issue? :) Sorry for finding all these errors ;)

**Comment by loicsander** [comment]
Oh, I see what went wrong with groups, this is solved now.

As for the mode crashing things, It’s rather annoying that there’s no traceback, it makes it really hard to have an idea of what’s messing up Robofont. 

Does it happen when you change the mode without regard to what you put in the cell or does it react badly only to mode removal?

**Comment by thomgb** [comment]
Changing the mode is fine. 
I looked into the code where the editing of the mode is, but I couldnt find it. Can you tell me where to look?

**Comment by loicsander** [comment]
Modes are gathered there: https://github.com/loicsander/Robofont-scripts/blob/master/PenBallWizard/PenBallWizard.roboFontExt/lib/penBallWizard.py#L415

But I’m not sure it will be of much help. Meanwhile, I’ve modified the way boolean operations are handled to catch errors. If I succeeded, you may not get the crashes anymore but an errorGlyph telling you a boolean operation went wrong (B). I’ve stumbled upon issues with booleanOperations as well, but one must remember that such geometry calculations are prone to all kind of mishaps, it’s complicated stuff.

But there’s another issue with modes and with arguments in general, they don’t get updated right away if you change them, you need to restart the extension or sometimes even Robofont to see the change taking effect…
