### ISSUE TITLE
ScaleFast: Adds Unicodes to existing glyphs 

### ISSUE THREAD

**Issue by frankrolf** [loicsander/Robofont-scripts#18]
When writing scaled glyphs into an existing UFO, some Unicodes values of existing glyphs are changed. (In my case Delta, Omega, mu).

**Comment by adrientetar** [comment]
> (In my case Delta, Omega, mu)

It seems to be a subset of those that changed in AGL 1.7, could it be different AGL version that was applied by the script?

**Comment by loicsander** [comment]
The updated version of ScaleFast should handled those in a nicer way. MutatorScale transfers unicodes from the source glyph to the scaled ones. I have yet to find a nice way to let the user decide wether the unicode should be retained or skipped (in case of [one —> onesuperior] for instance). Anyway, font.autoUnicodes() is no longer part of the game and that was the problem I think.
