### ISSUE TITLE
Scale Fast Extension not launching.

### ISSUE THREAD

**Issue by guidoferreyra** [loicsander/Robofont-scripts#19]
Any idea why Scale Fast is not launching? Nothing appears on the console.
Im on Yosemite and Robofont last build.

[EDIT]
Apparently Scale Fast launched but with a big delay, and breaking the UI of Robofont. Some fields and boxes turn transparent. see the image. The same happens with the UI in Scale Fast

![captura de pantalla 2015-06-10 a las 13 19 11](https://cloud.githubusercontent.com/assets/1755590/8087864/c4a50824-0f73-11e5-99b1-8641bf75fe2b.png)

**Comment by loicsander** [comment]
This is strange. Did you try with different fonts (in order to determine if the problem comes from reading the fonts or directly from the UI)?

**Comment by guidoferreyra** [comment]
Yes I've tried with several files including open source ufos like Source Serif. Perhaps I missing a library? Python Version?

**Comment by guidoferreyra** [comment]
This is the output in the log.
![captura de pantalla 2015-06-22 a la s 23 27 33](https://cloud.githubusercontent.com/assets/1755590/8297759/92c9513a-1936-11e5-8d35-878ac25c2461.PNG)

**Comment by miguelsousa** [comment]
@guidoferreyra was the font hinted with the FDK's `autohint`?

**Comment by loicsander** [comment]
Thank you for the log Guido, I’ll look into it as soon as I have a spare moment.

**Comment by uebele** [comment]
Same happens to me, I’m also on Yosemite and last Robofont build.

**Comment by guidoferreyra** [comment]
@miguelsousa no this log isn't from Source Serif. Now, I'm trying with Loic's Fengardo Redux but in Yosemite, the window doesn't appear and the log is empty.

**Comment by loicsander** [comment]
I may have found the reason of this issue. Latest commit is an attempt at fixing, you can try it out by updating.

**Comment by uebele** [comment]
still not working, sorry.

**Comment by loicsander** [comment]
Ok, new attempt. 4cf06f129828634c2b61726dec2a1c04b475c47c

**Comment by uebele** [comment]
It’s launching now! However, it’s not calculating any stems and when checking/unchecking the masters it crashes.

**Comment by guidoferreyra** [comment]
IT WORKS!! But partially.
The masters checkboxes don't check and uncheck visually, but works.
Also there is some small glitch in other checkboxes they disappear when marked.
the right panel presents the first issue of transparent fields.

I'm comparing with the video on vimeo to note what other thing probably isn't working. 

I'm in Yosemite.

**Comment by loicsander** [comment]
Small victory then. It’s tricky to try and figure out what goes wrong when I don’t see the problem, and it is even more strange that it happens differently although we seemingly have the same setup.

I’ll keep digging.

**Comment by guidoferreyra** [comment]
Great, tell me how can I help you. Screenshots, video, etc

**Comment by loicsander** [comment]
New attempt e50f80e9d681608ae2018fae95f058b0fafa56eb

**Comment by loicsander** [comment]
The blank fields are crashed vanilla List, and that’s what I’m working on. The checkbox part might be something else…

**Comment by guidoferreyra** [comment]
apparently, everything works fine for me. I will keep you posted.

**Comment by loicsander** [comment]
Cool, let me know if it holds.

**Comment by uebele** [comment]
yes, works fine for me too, thanks a lot!
