### ISSUE TITLE
PenBallWizzard extension in RoboFont 3

### ISSUE THREAD

**Issue by vinuel** [loicsander/Robofont-scripts#28]
Does the PenBallWizzard extension work with RoboFont 3? 
I get a traceback when launching it...

`Traceback (most recent call last):
​  File "penBallWizardController.py", line 8, in <module>
ModuleNotFoundError: No module named 'robofab'`

**Comment by gferreira** [comment]
see [roboDocs/PenBallWizard](http://github.com/roboDocs/PenBallWizard)

also available from [Mechanic2](http://robofontmechanic.com/)
