### ISSUE TITLE
Derivative Glyphs Builder 0.5.2: doesn’t build

### ISSUE THREAD

**Issue by LaPolice** [loicsander/Robofont-scripts#6]
Hi Loïc,

I was giving your script a try after reading the instructions and watching the video.
Everything works well, except when I hit "Build selected glyphs" nothing happens and I get this Output message:

Traceback (most recent call last):
  File "/Applications/RoboFont.app/Contents/Resources/lib/python2.7/vanilla/vanillaBase.py", line 204, in action_
    self.callback(sender)
  File "build-derivatives.py", line 840, in buildSelectedGlyphs
  File "build-derivatives.py", line 770, in makeGlyph
TypeError: a float is required

Thanks for sharing your work, best,

Mathieu

**Comment by loicsander** [comment]
Hi Mathieu, thanks for reporting back. Hard to tell what the matter exactly is with this traceback, but I tried something based on an assumption. Please update to the last version and tell me if the troubles go away. Otherwise, I’ll keep searching.

Thanks!

**Comment by LaPolice** [comment]
Hello Loïc,

It seems you successfully caught a TypeError as it now works smoothly on my side.
Thanks a lot for fixing this and enjoy Robothon if you're in the church of Python.

Bonne matinée,

Mathieu

**Comment by loicsander** [comment]
Content que l’erreur ait bien été identifiée!
