### ISSUE TITLE
support external packages to subscribe to a penBallWizard notifcation

### ISSUE THREAD

**Issue by typemytype** [loicsander/Robofont-scripts#9]
An external tool that is using a pen to draw or has a function to filter glyph data could subscribe to a notification that you send out while launching a PenBallWizard window

```Python
from mojo.events import postEvent

def launchWindow(self):
    externalFilterList = []
    postEvent("PenBallWizardSubscribeFilter", filterList=externalFilterList)
```

an external tool could then subscribe to the notification `PenBallWizardSubscribeFilter` and append a filter to your externalFilterList.

**Comment by loicsander** [comment]
I don’t see where you’re getting at with this, what use case do you have in mind? 

Anyway, I guess it’s pretty easy to implement, in __init__():

```python
self.w.bind('open', self.launchWindow)
```
?

**Comment by typemytype** [comment]
fe Outliner could register by subscribing the notification. Whenever your window opens you send the notification and Outliners adds 'outlineGlyph' and some arguments. This would add an other filter...

**Comment by loicsander** [comment]
Aha! I see, let’s try that.

**Comment by loicsander** [comment]
Added, I’m not sure if I did it properly, but you should be able to test it with the Outliner now.

**Comment by typemytype** [comment]
well, now you have to do something with the provided callbacks :)

**Comment by loicsander** [comment]
Okay, I think I’m missing a piece, event handling is not yet obvious to me, so I’ll go ahead and naïvely ask a newbie question :') 

Should it look something like this?


```python
class PenBallWizard:

&nbsp;&nbsp;&nbsp;&nbsp;def __init__(…)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;…
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;addObserver(self, 'addExternalFilter', 'PenBallWizardSubscribeFilter')

&nbsp;&nbsp;&nbsp;&nbsp;…

&nbsp;&nbsp;&nbsp;&nbsp;def addExternalFilter(self, notification):
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;# do stuff with given external filter list
```

**Comment by loicsander** [comment]
I got something working. Subscribing to the ```"PenBallWizardSubscribeFilter"``` event, you get back a method through ```notification['subscribeFilter']``` that allows you to add a filter.

```python
filterDict = {
    'filterObject': MyPen,
    # or 'module': ('module.myPen', 'MyPen')
    # or 'file': ('/path/to/file/myPen.py', 'myPen')
    'arguments': {'arg1': True}
}

subscribeFilter = notification['subscribeFilter']
subscribeFilter(myFilterName, filterDict)
```
